#!/bin/bash\n# Agent Startup Commands\n# Generated by configure_agent_mcps.py\n\n# Start Risk Manager Agent
export MCP_CONFIG_FILE=config/agent_mcps/risk_manager_mcps.yaml
export SERVICE_PORT=8002
python src/signal_service.py\n\n# Start Market/News Analyst Agent
export MCP_CONFIG_FILE=config/agent_mcps/market_news_analyst_mcps.yaml
export SERVICE_PORT=8003
python src/data_service.py\n\n# Start Trade Executor Agent
export MCP_CONFIG_FILE=config/agent_mcps/trade_executor_mcps.yaml
export SERVICE_PORT=8005
python src/market_executor_service.py\n\n# Start Parameter Optimizer Service
export MCP_CONFIG_FILE=config/agent_mcps/parameter_optimizer_mcps.yaml
export SERVICE_PORT=8006
python src/parameter_optimizer_service.py