#!/usr/bin/env python3
"""
Simplified deployment script that generates instructions for manual deployment
"""

server_ip = "91.99.103.119"

print("🚀 AI Trading System - Manual Deployment Instructions")
print("=" * 60)
print(f"Server IP: {server_ip}")
print()
print("📋 Step-by-Step Deployment:")
print()
print("1. SSH into the server (you may need to reset root password via Hetzner console):")
print(f"   ssh root@{server_ip}")
print()
print("2. Update the system:")
print("   apt update && apt upgrade -y")
print()
print("3. Install Docker and Docker Compose:")
print("   curl -fsSL https://get.docker.com -o get-docker.sh")
print("   sh get-docker.sh")
print("   curl -L \"https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose")
print("   chmod +x /usr/local/bin/docker-compose")
print()
print("4. Install dependencies:")
print("   apt install -y python3-pip git htop curl wget nodejs npm")
print("   curl -L https://go.dev/dl/go1.21.0.linux-amd64.tar.gz | tar -C /usr/local -xzf -")
print("   echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc")
print("   source ~/.bashrc")
print()
print("5. Clone the project:")
print("   cd /opt")
print("   git clone https://github.com/your-username/trajdar_bjorn.git ai-trading-system")
print("   cd ai-trading-system")
print()
print("6. Set up environment file:")
print("   cp .env.production .env.production.local")
print("   # Edit the file with your API keys if needed")
print()
print("7. Start the system:")
print("   docker-compose -f docker-compose.production.yml up -d")
print()
print("8. Check status:")
print("   docker-compose -f docker-compose.production.yml ps")
print("   curl http://localhost:8000/health")
print("   curl http://localhost:9000/health")
print()
print("🌐 Access URLs:")
print(f"   System: http://{server_ip}:8000")
print(f"   MCP Hub: http://{server_ip}:9000")
print()
print("🔑 Alternative: Use Hetzner Console")
print("1. Go to Hetzner Cloud Console")
print("2. Select your server 'ai-trading-prod'")
print("3. Click 'Console' to access the server directly")
print("4. Follow the steps above in the console")
print()
print("✅ Your server is ready for deployment!")