name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run all tests (unit, integration, performance) with coverage
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term --cov-report=html --tb=short

      - name: Generate TEST_REPORT.md
        run: |
          coverage report > TEST_REPORT.md

      - name: Check coverage threshold
        run: |
          coverage report --fail-under=90

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: warn

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
          if-no-files-found: warn

      - name: Upload TEST_REPORT.md
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: TEST_REPORT.md
          if-no-files-found: warn
